/**
 * Liveness API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface HealthSimulationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Instance info
     * Returns hostname, IP, port, and current health states
     * @endpoint get /
     */
    root(extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * Toggle custom health indicator
     * Set to true (UP) or false (DOWN)
     * @endpoint get /simulate/health/{state}
     * @param state 
     */
    setHealth(state: boolean, extraHttpRequestParams?: any): Observable<string>;

    /**
     * Toggle liveness probe
     * Set to true (CORRECT) or false (BROKEN)
     * @endpoint get /simulate/liveness/{state}
     * @param state 
     */
    setLiveness(state: boolean, extraHttpRequestParams?: any): Observable<string>;

    /**
     * Toggle readiness probe
     * Set to true (ACCEPTING_TRAFFIC) or false (REFUSING_TRAFFIC)
     * @endpoint get /simulate/readiness/{state}
     * @param state 
     */
    setReadiness(state: boolean, extraHttpRequestParams?: any): Observable<string>;

}
