/**
 * Liveness API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetail } from '../model/models';
import { Product } from '../model/models';
import { ProductRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProductsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete a product
     * 
     * @endpoint delete /products/{id}
     * @param id 
     */
    _delete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a new product
     * 
     * @endpoint post /products
     * @param productRequest 
     */
    create(productRequest: ProductRequest, extraHttpRequestParams?: any): Observable<Product>;

    /**
     * List all products
     * 
     * @endpoint get /products
     */
    getAll(extraHttpRequestParams?: any): Observable<Array<Product>>;

    /**
     * Get a product by ID
     * 
     * @endpoint get /products/{id}
     * @param id 
     */
    getById(id: string, extraHttpRequestParams?: any): Observable<Product>;

    /**
     * Update an existing product
     * 
     * @endpoint put /products/{id}
     * @param id 
     * @param productRequest 
     */
    update(id: string, productRequest: ProductRequest, extraHttpRequestParams?: any): Observable<Product>;

}
